name: projet_todo
description: Application Todo pour Master M1 2024-2025

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    flutter_localizations:  
    sdk: flutter
  
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  # SUPPRIMER la section fonts pour l'instant